routes/main/routes.py
import datetime
from __init__ import bcrypt, db
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user
from models import User, Tasks

from routes.main.forms import (LoginForm, RegistrationForm, RequestResetForm,
                               ResetPasswordForm, UpdateAccountInfoForm, TaskForm)
from routes.main.utils import save_picture, send_reset_email

main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
def homepage():
    return render_template("homepage.html")


@main.route("/profile", methods=["GET", "POST"])
def profile():
    if not current_user.is_authenticated:
        flash("You need to be logged in to view this page", "warning")
        return redirect(url_for("main.login"))

    form = TaskForm()

    tasks = User.query.get(int(current_user.id)).tasks

    for task in tasks:
        if task.end_date < datetime.datetime.now():
            if task.value < task.max_value:
                task.status = 'failed'
            elif task.value >= task.max_value:
                task.status = 'completed'

    db.session.commit()

    if request.method == 'POST':
        try:
            create_task = request.form['create_task']

            if create_task == 'true':
                new_task = Tasks(name="New Task", min_value=0, max_value=1, value=0,
                                 repeat="false", start_date=datetime.datetime.now(),
                                 end_date=datetime.datetime.now()+datetime.timedelta(days=1),
                                 status="in_progress", public="true", user_id=current_user.id)

                db.session.add(new_task)
                db.session.commit()
                db.session.remove()
                flash('A blank task has been created', 'success')
                return redirect(url_for('main.profile'))
        except Exception as e:
            pass

    if form.validate_on_submit():
        task_id = request.form['task_id']
        task = Tasks.query.get(int(task_id))

        task.name = form.name.data
        task.min_value = form.min_value.data
        task.max_value = form.max_value.data
        task.value = form.value.data
        task.repeat = form.repeat.data
        task.start_date = form.start_date.data
        task.end_date = form.end_date.data
        task.public = form.public.data

        db.session.commit()
        db.session.remove()
        flash('Your task has been updated!', 'success')
        return redirect(url_for('main.profile'))

    return render_template("profile.html", tasks=tasks, form=form)


@main.route("/search", methods=["GET", "POST"])
@main.route("/search/<username>", methods=["GET", "POST"])
def search(username: str = ""):
    if username:
        total_results = User.query.filter(User.username.like(
            '%' + username + '%')).count()
        users = User.query.filter(User.username.like(
            '%' + username + '%')).limit(10).all()
        if users:
            return render_template("search.html", users=users, total_results=total_results)
        else:
            flash("No one with that username exists", "warning")
    return render_template("search.html")


@main.route("/profile/<username>", methods=["GET", "POST"])
def other_profile(username: str = ""):

    user = User.query.filter_by(username=username).first()
    tasks = User.query.get(int(user.id)).tasks

    for task in tasks:
        if task.end_date < datetime.datetime.now():
            if task.value < task.max_value:
                task.status = 'failed'
            elif task.value >= task.max_value:
                task.status = 'completed'

    db.session.commit()

    return render_template("other_profile.html", user=user, tasks=tasks)


@main.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.homepage"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            db.session.remove()
            return (
                redirect(next_page) if next_page else redirect(
                    url_for("main.homepage"))
            )
        elif not user:
            flash("There is no account with that name", "warning")
        else:
            flash("Username and Password do not match", "warning")
    return render_template("login.html", title="Login", form=form)


@main.route("/logout", methods=["GET", "POST"])
def logout():
    if not current_user.is_authenticated:
        flash("You need to be logged in to view this page", "warning")
        return redirect(url_for("main.login"))
    logout_user()
    return redirect(url_for("main.homepage"))


@main.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.homepage"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        db.session.remove()
        user = User.query.filter_by(username=form.username.data).first()
        login_user(user)
        return redirect(url_for("main.login"))
    return render_template("register.html", title="Register", form=form)


@main.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@main.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        db.session.remove()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@main.route("/account_settings", methods=["GET", "POST"])
def account_settings():
    if not current_user.is_authenticated:
        flash("You need to be logged in to view this page", "warning")
        return redirect(url_for("main.login"))
    form = UpdateAccountInfoForm()
    refresh_flag = False
    if form.validate_on_submit():
        user = User.query.get(int(current_user.id))
        if form.picture.data:
            picture_file = save_picture(form.picture.data, locator=0)
            user.image_file = picture_file
            refresh_flag = True
        if (form.old_password.data or form.new_password.data or form.confirm_password.data):
            if form.new_password.data == form.confirm_password.data:
                hashed_password = bcrypt.generate_password_hash(
                    form.new_password.data).decode('utf-8')
                user.password = hashed_password
                refresh_flag = True
        if form.username.data != user.username:
            user.username = form.username.data
            refresh_flag = True
        if form.email.data != user.email:
            user.email = form.email.data
            refresh_flag = True
        if form.secondary_email.data != user.secondary_email:
            user.secondary_email = form.secondary_email.data
            refresh_flag = True
        if form.motto.data != user.motto:
            user.motto = form.motto.data
            refresh_flag = True
        if form.bio.data != user.bio:
            user.bio = form.bio.data
            refresh_flag = True
        if form.birthday.data != user.birthday:
            user.birthday = form.birthday.data
            refresh_flag = True
        if form.telephone_number.data != user.telephone_number:
            user.telephone_number = form.telephone_number.data
            refresh_flag = True
        if refresh_flag:
            db.session.commit()
            db.session.remove()
            flash('Your account settings has been updated!', 'success')
            return redirect(url_for('main.account_settings'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.secondary_email.data = current_user.secondary_email
        form.motto.data = current_user.motto
        form.bio.data = current_user.bio
        form.birthday.data = current_user.birthday
        form.telephone_number.data = current_user.telephone_number

    return render_template('account_settings.html', title='Account Info', form=form)

templates/account.html
  {% extends "layout.html" %} {% block content %}

<form method="POST" action="" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  <fieldset class="form-group">
    <div class="account-header">
      <div class="form-group">
        <label for="picture" class="rounded-circle"
          ><img
            class="rounded-circle"
            src="/static/assets/user_images/{{ current_user.image_file }}"
            width="120"
            height="120"
        /></label>
        {{ form.picture(class="form-control-file") }} {% if form.picture.errors
        %} {% for error in form.picture.errors %}
        <span class="text-danger">{{ error }}</span>
        {% endfor %} {% endif %}
        <button
          class=""
          style="display: none"
          id="pictureButton"
          type="submit"
        ></button>
      </div>
    </div>
    <div class="info-section">
      <div class="public-info-section section">
        <legend>Public Information</legend>
        {{ form.username.label }}
        <div class="form-group username input-group">
          {% if form.username.errors %} {{ form.username(class="form-control
          is-invalid") }}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="usernameButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.username(class="form-control") }} {% endif %}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="usernameButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
        </div>
        {{ form.motto.label }}
        <div class="form-group motto input-group">
          {% if form.motto.errors %} {{ form.motto(class="form-control
          is-invalid") }}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="mottoButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
          <div class="invalid-feedback">
            {% for error in form.motto.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.motto(class="form-control") }} {% endif %}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="mottoButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
        </div>
        {{ form.bio.label }}
        <div class="form-group bio input-group">
          {% if form.bio.errors %} {{ form.bio(class="form-control is-invalid")
          }}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="bioButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
          <div class="invalid-feedback">
            {% for error in form.bio.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.bio(class="form-control") }} {% endif %}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="bioButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
        </div>
        {{ form.birthday.label }}
        <div class="form-group birthday input-group">
          {% if form.birthday.errors %} {{ form.birthday(class="form-control
          is-invalid") }}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="birthdayButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
          <div class="invalid-feedback">
            {% for error in form.birthday.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.birthday(class="form-control") }} {% endif %}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="birthdayButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
        </div>
      </div>
      <div class="private-info-section section">
        <legend>Private Information</legend>
        {{ form.email.label }}
        <div class="form-group email input-group">
          {% if form.email.errors %} {{ form.email(class="form-control
          is-invalid") }}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="emailButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
          <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.email(class="form-control") }} {% endif %}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="emailButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
        </div>
        <legend style="margin-top: 2vh">
          Change Password
          <a
            style="font-size: x-small"
            href="{{ url_for('main.reset_request') }}"
            >Forgot Password</a
          >
        </legend>
        {{ form.old_password.label }}
        <div class="form-group old_password input-group">
          {% if form.old_password.errors %} {{
          form.old_password(class="form-control is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.old_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.old_password(class="form-control ") }} {% endif %}
        </div>
        {{ form.new_password.label }}
        <div class="form-group new_password input-group">
          {% if form.new_password.errors %} {{
          form.new_password(class="form-control is-invalid") }}
          <div class="invalid-feedback">
            {% for error in form.new_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.new_password(class="form-control ") }} {% endif %}
        </div>
        {{ form.confirm_password.label }}
        <div class="form-group confirm_password input-group">
          {% if form.confirm_password.errors %} {{
          form.confirm_password(class="form-control is-invalid") }}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="confirmButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
          <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% else %} {{ form.confirm_password(class="form-control ") }} {% endif
          %}
          <div class="input-group-append">
            <button class="btn btn-secondary" id="confirmButton" type="submit">
              <i class="fa-solid fa-check"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </fieldset>
</form>
<div id="originalUserInformation" style="display: none">
  <input
    type="text"
    id="originalusername"
    value="{{ current_user.username }}"
  />
  <input type="text" id="originalmotto" value="{{ current_user.motto }}" />
  <input type="text" id="originalbio" value="{{ current_user.bio }}" />
  <input
    type="text"
    id="originalbirthday"
    value="{{ current_user.birthday }}"
  />
  <input type="text" id="originalemail" value="{{ current_user.email }}" />
</div>
<script type="text/javascript">
  window.addEventListener(
    "keydown",
    function (e) {
      if (
        e.keyIdentifier == "U+000A" ||
        e.keyIdentifier == "Enter" ||
        e.keyCode == 13
      ) {
        if (
          e.target.nodeName == "INPUT" &&
          (e.target.id == "username" ||
            e.target.id == "email" ||
            e.target.id == "motto" ||
            e.target.id == "bio" ||
            e.target.id == "birthday" ||
            e.target.id == "old_password" ||
            e.target.id == "new_password" ||
            e.target.id == "confirm_password")
        ) {
          e.preventDefault();
          return false;
        }
      }
    },
    true
  );
</script>
<!-- Custom Js -->
<script src="/static/js/user_account.js" type="text/javascript"></script>
{% endblock content %}

templates/create_task.html
{% extends 'layout.html'%}
{% block content%}
<section class="container">
   <div class="row">
      <div class="col" a>
         <form method="POST" action="">
            <p>
               {{ form.name.label }}<br>
               {{ form.name(size =32) }}
            </p>
            <p>
               {{ form.end_date.label }}<br>
               {{ form.end_date(size=32) }}
            </p>
               <p>
               {{ form.start_date.label }}<br>
               {{ form.start_date(size=32) }}
            </p>
            <p>
               {{ form.status.label }}<br>
               {{ form.status() }}
            </p>


            <p>{{ form.submit() }}</p>
         </form>
      </div>
   </div>
</section>
{% endblock%}

templates/homepage.html
{% extends "layout.html" %} {% block elements%}
<div>
  {% endblock %} {% block content %}

  <div class="homepage">
    <div class="header">
      <div class="inner-header flex">
        <div class="homepage-top">
          <h1>Welcome To <span>ToDooz!</span></h1>
        </div>

        <div class="item-container">
          {% if not current_user.is_authenticated %}
          <a href="{{ url_for('main.login') }}" class="item">
            <i class="fa-solid fa-plus"></i>
            <h2>Start Creating Tasks Now!</h2>
          </a>
          {% else %}
          <a href="{{ url_for('main.profile') }}" class="item">
            <i class="fa-solid fa-list-check"></i>
            <h2>Profile</h2>
          </a>
          {% endif %}
          <a href="{{ url_for('main.search') }}" class="item">
            <i class="fa-solid fa-magnifying-glass"></i>
            <h2>Search For Other People's Tasks!</h2>
          </a>
        </div>
      </div>

      <div>
        <svg
          class="waves"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          viewBox="0 24 150 28"
          preserveAspectRatio="none"
          shape-rendering="auto"
        >
          <defs>
            <path
              id="gentle-wave"
              d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"
            />
          </defs>
          <g class="parallax">
            <use
              xlink:href="#gentle-wave"
              x="48"
              y="0"
              fill="rgba(255,255,255,0.7"
            />
            <use
              xlink:href="#gentle-wave"
              x="48"
              y="3"
              fill="rgba(255,255,255,0.5)"
            />
            <use
              xlink:href="#gentle-wave"
              x="48"
              y="5"
              fill="rgba(255,255,255,0.3)"
            />
            <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
          </g>
        </svg>
      </div>
    </div>
  </div>
  {%endblock%}
</div>

templates/layout.html
<!DOCTYPE html>
<html>
  {% block head %}
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link
      rel="icon"
      type="image/x-icon"
      href="/static/assets/site_images/logo.png"
    />

    {% if title %}
    <title>ToDooz - {{ title }}</title>
    {% else %}
    <title>ToDooz</title>
    {% endif %}

    <!-- Bootstrap CSS CDN -->
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    <!-- Font Awesome -->
    <script
      src="https://kit.fontawesome.com/ade146be62.js"
      crossorigin="anonymous"
    ></script>
    <!-- Custom CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
  </head>
  {% endblock head %}
  <body>
    <div class="wrapper">
      {% block sidebar %}
      <!-- Sidebar Holder -->
      <nav id="sidebar">
        <a class="home" href="{{ url_for('main.homepage') }}">
          <div class="sidebar-header">
            <h3>ToDooz</h3>
            <strong>TDz</strong>
          </div>
        </a>

        <ul class="list-unstyled components">
          <li>
            <a href="{{ url_for('main.profile') }}">
              <i class="fa-solid fa-user"></i>
              Profile
            </a>
          </li>
        </ul>

        <ul class="list-unstyled CTAs">
          {% if current_user.is_authenticated %}
          <li class="Account">
            <div class="btn-group dropend">
              <button
                type="button"
                class="btn btn-primary dropdown-toggle"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <img
                  class="rounded-circle"
                  src="/static/assets/user_images/{{ current_user.image_file }}"
                  width="40"
                  height="40"
                /><span>{{ current_user.username }}</span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <a
                    class="dropdown-item"
                    href="{{ url_for('main.account_settings') }}"
                    >Account Settings</a
                  >
                </li>
                <li>
                  <a class="dropdown-item" href="{{ url_for('main.logout') }}"
                    >Logout</a
                  >
                </li>
              </ul>
            </div>
          </li>
          {% else %}
          <li>
            <a href="{{ url_for('main.login') }}"
              ><i class="fa-solid fa-arrow-right-to-bracket"></i
              ><span>LogIn / Register </span></a
            >
          </li>
          {% endif %}
          <li class="search-bar">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">@</span>
              </div>
              <input
                id="userSearchTermSideBar"
                name="search"
                type="text"
                class="form-control"
                placeholder="Username"
                aria-label="searchUsername"
                aria-describedby="basic-addon1"
              />
              <div class="input-group-append">
                <button
                  class="btn btn-secondary"
                  type="submit"
                  id="gamertagSubmit"
                >
                  <i class="fa fa-search"></i>
                </button>
              </div>
            </div>
          </li>
          <li class="search-button">
            <a href="{{ url_for('main.search') }}"
              ><i class="fa fa-search"></i
            ></a>
          </li>
          <li>
            <a
              href="https://github.com/MScheiterle/Capstone-Project"
              target="_blank"
              class="github"
              ><i class="fab fa-github"></i
              ><span
                >View The Github
                <i class="fa-solid fa-arrow-up-right-from-square"></i></span
            ></a>
          </li>
        </ul>
      </nav>
      {% endblock sidebar %}

      <!-- Page Content Holder -->
      <div id="content">
        {% block elements %}
        <div id="elements">
          {% endblock elements %}{% block content %}{% endblock %}
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
        <div class="error-bar">
          {% if "warning" in category%}
          <i class="fa-solid fa-triangle-exclamation"></i>
          {% elif "success" in category%}
          <i class="fa-solid fa-check"></i>
          {% endif %} {{ message }}
        </div>
        {% endfor %} {% endif %} {% endwith %}
        <button type="button" id="sidebarCollapse" class="btn btn-primary">
          <i class="fa-solid fa-align-left"></i>
        </button>
      </div>
    </div>

    {% block extra_content %}{% endblock %}

    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <!-- Cookies -->
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
    <!-- Custom Js -->
    <script src="/static/js/script.js" type="text/javascript"></script>
  </body>
</html>

templates/login.html
{% extends "layout.html" %} {% block content %}

<form method="POST" action="">
  {{ form.hidden_tag() }}
  <fieldset class="form-group">
    <div class="section public-info-section">
      <legend class="border-bottom mb-2">Log In</legend>
      <div class="form-group">
        {{ form.username.label(class="form-control-label") }} {% if
        form.username.errors %} {{ form.username(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.username(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="login-bottom">
        <div style="display: flex; align-items: center">
          <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
          </div>
          <div class="form-check">
            {{ form.remember(class="form-check-input") }} {{
            form.remember.label(class="form-check-label") }}
          </div>
        </div>
        <div style="display: flex; padding-top: 10px; flex-direction: column">
          <small>
            Need An Account?
            <a class="ml-2 unset" href="{{ url_for('main.register') }}"
              ><span>SIGN UP NOW</span></a
            >
          </small>
          <small>
            Forgot password?
            <a class="ml-2 unset" href="{{ url_for('main.reset_request') }}"
              ><span>RESET PASSWORD</span></a
            >
          </small>
        </div>
      </div>
    </div>
  </fieldset>
</form>
{% endblock %}

templates/reset_request.html
{% extends "layout.html" %} {% block content %}
<form method="POST" action="">
  {{ form.hidden_tag() }}
  <fieldset class="form-group">
    <div class="section public-info-section">
      <legend class="border-bottom mb-2">Reset Password</legend>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group" style="padding-top: 10px;">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </div>
  </fieldset>
</form>
{% endblock content %}

templates/search.html
{% extends "layout.html" %} {% block content %}
<div class="search-page">
  <div class="input-group search-page-bar">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">@</span>
    </div>
    <input
      id="userSearchTermSearchPage"
      name="search"
      type="text"
      class="form-control"
      placeholder="Username"
      aria-label="searchUsername"
      aria-describedby="basic-addon1"
    />
    <div class="input-group-append">
      <button class="btn btn-secondary" type="submit" id="gamertagSubmitMain">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  Showing {{ users|count }} out of {{ total_results if total_results else "0" }}

  <div class="item-container">
    {% if users %} {% for user in users %}
    <a
      href="{{ url_for('main.other_profile', username=user.username ) }}"
      class="result-item item"
    >
      <img
        class=""
        src="/static/assets/user_images/{{ user.image_file }}"
        height="100%"
      />
      <div class="result-info">
        <h2>{{ user.username }}</h2>
      </div>
    </a>
    {% endfor %} {% endif %}
  </div>
  <!-- Custom Js -->
  <script src="/static/js/search.js" type="text/javascript"></script>
  {% endblock %}
</div>

templates/user_account.html
{% extends "layout.html" %}{% block content %}
Loads another user's account
{%endblock%}

templates/your_tasks.html
 {% extends "layout.html" %} {% block content %}


{% endblock content %}